openapi: 3.0.1
info:
  title: l10n.dev/api documentation.
  description: "## AI-powered localization\r

    \r

    To access the API, please sign in and generate your API Key on the [API
    Keys](https://l10n.dev/ws/keys) page.\r

    \r

    You’ll receive **30,000 characters free** for 3 days after signing up. Our
    service is more affordable than other machine translation solutions. [See
    pricing](https://l10n.dev/#pricing)\r\n"
  version: 1.0.0
servers:
  - url: https://localhost:7032/
paths:
  /languages/predict:
    get:
      tags:
        - Languages
      summary: Predict language code.
      description: Predicts the language code by input.
      parameters:
        - name: input
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            default: 10
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LanguagePredictionResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    nullable: true
                  title:
                    type: string
                    nullable: true
                  status:
                    type: integer
                    format: int32
                    nullable: true
                  detail:
                    type: string
                    nullable: true
                  instance:
                    type: string
                    nullable: true
                example:
                  type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                  title: One or more validation errors occurred.
                  status: 400
                  traceId: ""
                  errors: {}
      security:
        - ApiKey: []
  /translate:
    post:
      tags:
        - JSON Translation
      summary: Translate source strings to the target language.
      description: Translates the provided source strings into the target language
        specified in the request. The maximum request size allowed is 10 MB.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TranslationRequest"
          text/json:
            schema:
              $ref: "#/components/schemas/TranslationRequest"
          application/*+json:
            schema:
              $ref: "#/components/schemas/TranslationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TranslationResult"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    nullable: true
                  title:
                    type: string
                    nullable: true
                  status:
                    type: integer
                    format: int32
                    nullable: true
                  detail:
                    type: string
                    nullable: true
                  instance:
                    type: string
                    nullable: true
                example:
                  type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                  title: One or more validation errors occurred.
                  status: 400
                  traceId: ""
                  errors: {}
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    nullable: true
                  title:
                    type: string
                    nullable: true
                  status:
                    type: integer
                    format: int32
                    nullable: true
                  detail:
                    type: string
                    nullable: true
                  instance:
                    type: string
                    nullable: true
                example:
                  type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                  title: Unauthorized
                  status: 401
                  traceId: ""
                  detail: ""
        "402":
          description: Payment Required
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    nullable: true
                  title:
                    type: string
                    nullable: true
                  status:
                    type: integer
                    format: int32
                    nullable: true
                  detail:
                    type: string
                    nullable: true
                  instance:
                    type: string
                    nullable: true
                example:
                  type: https://tools.ietf.org/html/rfc9110#section-15.5.3
                  title: Payment Required
                  status: 402
                  traceId: ""
                  detail: Insufficient balance. You need 9999 characters to proceed with the
                    translation. Please visit https://l10n.dev/#pricing to
                    purchase a character package and try again.
                  data:
                    requiredCharactersForTranslation: 9999
        "413":
          description: Payload Too Large
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    nullable: true
                  title:
                    type: string
                    nullable: true
                  status:
                    type: integer
                    format: int32
                    nullable: true
                  detail:
                    type: string
                    nullable: true
                  instance:
                    type: string
                    nullable: true
                example:
                  type: https://tools.ietf.org/html/rfc9110#section-15.5.14
                  title: Content Too Large
                  status: 413
                  traceId: ""
                  detail: ""
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    nullable: true
                  title:
                    type: string
                    nullable: true
                  status:
                    type: integer
                    format: int32
                    nullable: true
                  detail:
                    type: string
                    nullable: true
                  instance:
                    type: string
                    nullable: true
                example:
                  type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                  title: An error occurred while processing your request.
                  status: 500
                  traceId: ""
                  errorCode: aa22bb11ff
      security:
        - ApiKey: []
components:
  schemas:
    FinishReason:
      enum:
        - stop
        - length
        - contentFilter
        - insufficientBalance
        - error
      description: The finish reason of the translation.
    Language:
      type: object
      properties:
        code:
          type: string
          description: The language code.
          nullable: true
        name:
          type: string
          description: The name of the language in English.
          nullable: true
    LanguagePredictionResponse:
      required:
        - languages
      type: object
      properties:
        languages:
          type: array
          items:
            $ref: "#/components/schemas/Language"
    TerminologyEntry:
      required:
        - term
      type: object
      properties:
        term:
          type: string
        synonyms:
          type: array
          items:
            type: string
          description: The list of disallow synonyms for the term. This allows you to
            specify which words should be replaced by the term, providing more
            control over the usage of the term in translations.
    TranslationRequest:
      required:
        - sourceStrings
        - targetLanguageCode
      type: object
      properties:
        sourceStrings:
          type: object
          additionalProperties:
            type: string
          description: The i18n JSON format source strings for translation, supporting
            deep nested objects.
        targetLanguageCode:
          type: string
          description: "The code of the target language. Example: zh, zh-CHT, zh-Hans-CN."
        useContractions:
          type: boolean
          description: Indicates whether to use grammar contractions. Using contractions
            makes the translation less formal.
          default: true
        useShortening:
          type: boolean
          description: Indicates whether to use shortened forms if the translation is
            longer than the source text.
          default: false
        terminology:
          type: array
          items:
            $ref: "#/components/schemas/TerminologyEntry"
          description: A list of terms to use in translation. Using consistent terminology
            improves readability and comprehension.
          nullable: true
      example:
        targetLanguageCode: es
        useContractions: true
        useShortening: true
        sourceStrings:
          key_one: apple
          key_hasCount_one: "{{count}} apple"
          key_hasCount_few: "{{count}} apples"
          key_hasCount_other: "{{count}} apples"
          key_interval: (1){one apple};(2-7){a few apples};(7-inf){a lot of apples};
          key_hasPlural_interval: (1){one apple};(2-4){apples};(4-inf){apples};
          key_useShortening: Please contact your admin.
          key_useShortening2: No max. length
          key_useContractions: What's my current month's costs?
          key_hasDateAndTime: The report was generated on 02/22/2025 at 3:45 PM.
          key_hasInner:
            title: Configure options of {{ title }}
            message.isRequired: The {{ title }} option is required. Please select it.
          key_popularPhrase: I love you!
          key_hasCrLfTab: |-
            AI can preserve line breaks 
             and tabs 	 in text.
          key_hasInnerHtml: l10n.dev translates <strong>i18n</strong> files <span
            class="cyan">for developers</span> and <span
            class="yellow">localization teams</span>.
          key_hasNumber: The total amount is 1,234,567.89.
          intlDateTime: Current date and time is {{val, datetime}}
    TranslationResult:
      required:
        - targetLanguageCode
        - usage
        - completedChunks
        - totalChunks
      type: object
      properties:
        targetLanguageCode:
          type: string
          description: "The code of the target language. Example: zh, zh-CHT, zh-Hans-CN."
        translations:
          type: object
          additionalProperties:
            type: string
          description: The translation result in i18n JSON format.
        usage:
          $ref: "#/components/schemas/TranslationUsage"
        finishReason:
          $ref: "#/components/schemas/FinishReason"
        completedChunks:
          type: integer
          description: The number of completed chunks in the translation.
          format: int32
        totalChunks:
          type: integer
          description: The total number of chunks in the translation.
          format: int32
    TranslationUsage:
      type: object
      properties:
        charsUsed:
          type: integer
          format: int32
        details:
          $ref: "#/components/schemas/UsageDetails"
      description: Balance usage details.
    UsageDetails:
      type: object
      properties:
        terminologyCharCount:
          type: integer
          format: int32
        sourceStringsCharCount:
          type: integer
          format: int32
  securitySchemes:
    ApiKey:
      type: apiKey
      description: Paste API Key into the Value field to authorize requests.
      name: X-API-Key
      in: header
security:
  - ApiKey: []
tags:
  - name: Files
    description: This API allows users to manage translation-related files and
      currently supports i18n JSON files as the format for translations,
      ensuring efficient localization workflows.
  - name: I18N File Translation
    description: <p>This API provides endpoints for managing file translation jobs,
      including:</p><ul><li>Start a new translation job from the source language
      to target languages.</li><li>Monitor the status of an ongoing translation
      job. Use long polling for real-time updates.</li><li>Download translated
      files after the translation job has completed
      successfully.</li></ul><p>This workflow ensures efficient file translation
      management and seamless integration into your localization processes.</p>
  - name: Languages
    description: AI supports <b>12</b> languages with <b>Strong</b> proficiency,
      <b>53</b> with <b>High</b> proficiency, and <b>100</b> with
      <b>Moderate</b> proficiency. Other languages have limited
      support.</br></br>For languages in the <b>Strong</b> category, AI have
      excellent translation capabilities. It can handle complex sentence
      structures, nuanced meanings, and varied contexts with high accuracy. It
      can provide natural-sounding translations for a wide range of text types,
      including formal, informal, and technical language, and It has an in-depth
      understanding of the cultural and linguistic subtleties. Examples include
      English, Spanish, French, German, Chinese, and Russian.</br></br>For
      languages in the <b>High</b> category, AI am proficient in translation but
      might face occasional challenges with more complex or specialized texts or
      idiomatic expressions. However, It can still deliver accurate translations
      for most conversational, literary, or informal texts.</br></br>In
      languages with <b>Moderate</b> understanding, AI translations are usually
      accurate for general texts and basic conversation, but It may struggle
      with highly technical, literary, or culturally complex content. AI can
      help with basic communication and common expressions, but translations
      might require closer verification for more challenging
      material.</br></br>For languages in the <b>Limited</b> category, AI
      translation abilities are basic. While It can handle only common words,
      short phrases, and everyday conversations.
  - name: JSON Translation
